# Generated by Django 4.2.21 on 2025-06-16 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='employee_id',
            new_name='emp_id',
        ),
    ]
